import os
import time
import random
def clear_terminal():
    # Check the operating system and use the appropriate command
    if os.name == 'nt':  # For Windows
        os.system('cls')
    else:  # For macOS and Linux
        os.system('clear')
runsGuest = 0
runsHome = 0
battersBox = """
          +---------+ +---------+ +---------+ +---------+ +---------+
          |         | |         | |         | |         | |         |
          |    1    | |    6    | |   11    | |   16    | |   21    |
          |         | |         | |         | |         | |         |
          +---------+ +---------+ +---------+ +---------+ +---------+
          +---------+ +---------+ +---------+ +---------+ +---------+
          |         | |         | |         | |         | |         |
          |    2    | |    7    | |   12    | |   17    | |   22    |
          |         | |         | |         | |         | |         |
          +---------+ +---------+ +---------+ +---------+ +---------+
          +---------+ +---------+ +---------+ +---------+ +---------+
          |         | |         | |         | |         | |         |
          |    3    | |    8    | |   13    | |   18    | |   23    |
          |         | |         | |         | |         | |         |
          +---------+ +---------+ +---------+ +---------+ +---------+
          +---------+ +---------+ +---------+ +---------+ +---------+
          |         | |         | |         | |         | |         |
          |    4    | |    9    | |   14    | |   19    | |   24    |
          |         | |         | |         | |         | |         |
          +---------+ +---------+ +---------+ +---------+ +---------+
          +---------+ +---------+ +---------+ +---------+ +---------+
          |         | |         | |         | |         | |         |
          |    5    | |   10    | |   15    | |   20    | |   25    |
          |         | |         | |         | |         | |         |
          +---------+ +---------+ +---------+ +---------+ +---------+

"""
field = f"""
     .....................................
     .....................................
     ..SCOREBOARD:........................
     ..Home: {runsHome}............................
     ..Away: {runsGuest}............................
     ..............~~~~~~~~~..............
     ...........~~~.........~~~...........
     ..........~~.............~~..........
     .........~................~.........
     ........~......../\.........~........
     .......~~.......|  |........~~.......
     .......~......... . .........~.......
     ......~......... ... .........~......
     ......~........ ..... ........~......
     .....~........ ... ... ........~.....
     .....~....... ...   ... .......~.....
     .....~...... ...     ... ......~.....
     .....~.../\ ...       .../\....~.....
     ....~~..|  |..    P    .|  |...~~....
     ..... ..... ...       ... ..... .....
     ..... ...... ...     ... ...... .....
     ..... ....... ...   ... ....... .....
     ..... ........ ... ... ........ .....
     ...... ........ ..... ........ ......
     ...... ......... ... ......... ......
     ....... ........./\ ......... .......
     .......  .......|  |........  .......
     ........ .................. ........
     ......... ................ .........
     ..........  .............  ..........
     ............  .........   ...........
     ..............         ..............
     .....................................
     .....................................
     .....................................
     .....................................
     .....................................
"""
fieldOne = f""".....................................
     .....................................
     ..SCOREBOARD:........................
     ..Home: {runsHome}............................
     ..Away: {runsGuest}............................
     ..............~~~~~~~~~..............
     ...........~~~.........~~~...........
     ..........~~.............~~..........
     .........~................~.........
     ........~......../\.........~........
     .......~~.......|  |........~~.......
     .......~......... . .........~.......
     ......~......... ... .........~......
     ......~........ ..... ........~......
     .....~........ ... ... ........~.....
     .....~....... ...   ... .......~.....
     .....~...... ...     ... ......~.....
     .....~.../\ ...       .../\....~.....
     ....~~..|  |..    P    .|:)|...~~....
     ..... ..... ...       ... ..... .....
     ..... ...... ...     ... ...... .....
     ..... ....... ...   ... ....... .....
     ..... ........ ... ... ........ .....
     ...... ........ ..... ........ ......
     ...... ......... ... ......... ......
     ....... ........./\ ......... .......
     .......  .......|  |........  .......
     ........ .................. ........
     ......... ................ .........
     ..........  .............  ..........
     ............  .........   ...........
     ..............         ..............
     .....................................
     .....................................
     .....................................
     .....................................
     ....................................."""
fieldTwo = f""".....................................
     .....................................
     ..SCOREBOARD:........................
     ..Home: {runsHome}............................
     ..Away: {runsGuest}............................
     ..............~~~~~~~~~..............
     ...........~~~.........~~~...........
     ..........~~.............~~..........
     .........~................~.........
     ........~......../\.........~........
     .......~~.......|:)|........~~.......
     .......~......... . .........~.......
     ......~......... ... .........~......
     ......~........ ..... ........~......
     .....~........ ... ... ........~.....
     .....~....... ...   ... .......~.....
     .....~...... ...     ... ......~.....
     .....~.../\ ...       .../\....~.....
     ....~~..|  |..    P    .|:)|...~~....
     ..... ..... ...       ... ..... .....
     ..... ...... ...     ... ...... .....
     ..... ....... ...   ... ....... .....
     ..... ........ ... ... ........ .....
     ...... ........ ..... ........ ......
     ...... ......... ... ......... ......
     ....... ........./\ ......... .......
     .......  .......|  |........  .......
     ........ .................. ........
     ......... ................ .........
     ..........  .............  ..........
     ............  .........   ...........
     ..............         ..............
     .....................................
     .....................................
     .....................................
     .....................................
     ....................................."""
fieldThree = f""".....................................
     .....................................
     ..SCOREBOARD:........................
     ..Home: {runsHome}............................
     ..Away: {runsGuest}............................
     ..............~~~~~~~~~..............
     ...........~~~.........~~~...........
     ..........~~.............~~..........
     .........~................~.........
     ........~......../\.........~........
     .......~~.......|:)|........~~.......
     .......~......... . .........~.......
     ......~......... ... .........~......
     ......~........ ..... ........~......
     .....~........ ... ... ........~.....
     .....~....... ...   ... .......~.....
     .....~...... ...     ... ......~.....
     .....~.../\ ...       .../\....~.....
     ....~~..|:)|..    P    .|:)|...~~....
     ..... ..... ...       ... ..... .....
     ..... ...... ...     ... ...... .....
     ..... ....... ...   ... ....... .....
     ..... ........ ... ... ........ .....
     ...... ........ ..... ........ ......
     ...... ......... ... ......... ......
     ....... ........./\ ......... .......
     .......  .......|  |........  .......
     ........ .................. ........
     ......... ................ .........
     ..........  .............  ..........
     ............  .........   ...........
     ..............         ..............
     .....................................
     .....................................
     .....................................
     .....................................
     ....................................."""
currentField = """"""
batterDec = 0
pitcherDec = 0
hits = 0
inning = 0
topBot = 0 #Top of the inning is 0 Bottom of the inning is 1
#.5 will be top of the inning and 1 will be bottom
runsGuest = 0
runsHome = 0
strikes = 0
balls = 0
outs = 0
#_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
#Functions

def PitcherChoice():
    global pitcherDec
    x = 1
    while x > 0:
        z = 1
        print(battersBox,"ok pitcher where would you like to throw?")
        pitcherDec = input()
        while z != 0:
            y = input("Are you sure?(Y or N)\n")
            if y.upper() == "Y":
                x = 0
                z = 0
            elif y.upper() == "N":
                z = 0
            else:
                print("Didn't understand. Type in the form of Y or N (not caps sensitive)")
def BattersChoice():
    global batterDec
    x = 1   
    while x > 0:
        z = 1
        print (battersBox, "OK batter where do you think the pitcher threw?")
        batterDec = input()
        while z != 0:
            y = input("Are you sure?(Y or N)\n")
            if y.upper() == "Y":
                x = 0
                z = 0
            elif y.upper() == "N":
                z = 0
            else:
                print("Didn't understand. Type in the form of Y or N (not caps sensitive)")
def CheckforUpDown():
    if batterDec % 5 == 0:
        return("down")
    if batterDec in [1,6,11,16,21]:
        return("up")
def Where_is_it(bat, pit): #This will take the batter and pitcher decision and will return a number 1-9 of where the pitch is compared to the bat (5 is the middle of a 3-3 grid and refers to the bat and ball are on the same gridspace)
    if CheckforUpDown == down: #don't do +1

    if CheckforUpDown == up: #don't do -1

    else:# Do it all

def CheckForHit(x,y):#This Function Should Return What type of hit (HR,1,2,3)
    global hits
    def Corner():#Call this when the ball is on one of the corners to return whether its a hit
        check = random.randint(1,10)
        if check <= 3:
            return("Hit")
        else:
            return("Miss")
    def NextTo():#Call this when the ball is next to the bat (up,down,left,right) to return whether its a hit
        check = random.randint(1,2)
        if check == 1:
            return("Hit")
        else:
            return("Miss")


def Reset():
    global hits
    global currentField
    global inning
    global topBot
    hits = 0
    currentField = field
    inning += .5
    if topBot == 0:
        topBot += 1
    else:
        topBot = 0
    print("Alright thats 3 outs we're switching sides!")

    time.sleep(5)
    clear_terminal()
def Hit():
    global currentField
    global runsGuest
    global runsHome
    if hits == 1:
            currentField = fieldOne
            print(currentField)
            print("The pitch got hit and now there's a runner at first")
    elif hits == 2:
        currentField = fieldTwo
        print(currentField)
        print("The pitch got hit and now there's a runner on first and second!")
    elif hits == 3:
        currentField = fieldThree
        print(currentField)
        print("The pitch got hit and now the bases are loaded")
    elif hits >= 4:
        currentField = fieldThree
        print(currentField)
        print("The pitch got hit and the runner at 3rd scored!")
        if topBot == 0:
            runsGuest +=1
        else:
            runsHome += 1
def Miss():
    global strikes
    global outs
    strikes += 1
    print(f"Batter you swung and missed .Thats strike {strikes}!")
    print(f"The Pitch threw {pitcherDec} and you swung {batterDec}.")
    if strikes == 3:
        outs += 1
        print(f"Sorry Batter you struck out thats {outs} outs")
    if outs == 3:
        print("Sorry Batter thats 3 outs time to switch")
        Reset()
def GameOver():
    print(f"""Game Over!!!!
       Final score Home:{runsHome}
                   Guest{runsGuest} """)
    if runsGuest < runsHome:
        print("The Home team takes the win!")
    elif runsGuest > runsHome:
        print("The Guest team shows up and wins!")
    else:
        print("ANNNDD thats a tie.(sigh) I'm sure it was hard fought")
    print("\n\n\n\nAnd that was the game I hope you had fun! Run the program again to play again.(You go get that rematch :)")




#__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
#Main Game
clear_terminal()
print("\n\n\n\n                 Welcome to Baseball Mania 1!\nChoose who is Guest(batting first) and who is Home(pitching first)")
input("Click enter when you are ready\n")
print("Now how this game works is the pitcher will decide where to throw a pitch. Then the batter will guess where the pitch will be.\nIf the batter guesses right they get a hit and a man on base. If they guess wrong they will get a strike, three strikes is an out and 3 outs switch sides")
input("Hit enter when you are ready to conitinue")
clear_terminal()
while inning <= 9.5:
    input("\n\n Now batter turn around and pitcher hit enter when you are ready\n")
    PitcherChoice()
    clear_terminal()
    BattersChoice()
    print("Here's what happened")
    time.sleep(1)
    if CheckForHit(batterDec,pitcherDec) == "Hit":
        Hit()
    else:
        Miss()
GameOver()

