import os
def clear_terminal():
    # Check the operating system and use the appropriate command
    if os.name == 'nt':  # For Windows
        os.system('cls')
    else:  # For macOS and Linux
        os.system('clear')

battersBox = """
          ______________________________________________________
          |                |                   |                |
          |                |                   |                |
          |                |                   |                |
          |        1       |         2         |        3       |
          |                |                   |                |
          |                |                   |                |
          -------------------------------------------------------
          |                |                   |                |
          |                |                   |                |
          |                |                   |                |
          |        4       |         5         |        6       |
          |                |                   |                |
          |                |                   |                |
          -------------------------------------------------------
          |                |                   |                |
          |                |                   |                |
          |                |                   |                |
          |        7       |         8         |        9       |
          |                |                   |                |
          |                |                   |                |
          _______________________________________________________
"""
field = """
     .....................................
     .....................................
     ..SCOREBOARD:........................
     ..Home: 0............................
     ..Away: 0............................
     ..............~~~~~~~~~..............
     ...........~~~.........~~~...........
     ..........~~.............~~..........
     .........~................~.........
     ........~......../\.........~........
     .......~~.......|  |........~~.......
     .......~......... . .........~.......
     ......~......... ... .........~......
     ......~........ ..... ........~......
     .....~........ ... ... ........~.....
     .....~....... ...   ... .......~.....
     .....~...... ...     ... ......~.....
     .....~.../\ ...       .../\....~.....
     ....~~..|  |..    P    .|  |...~~....
     ..... ..... ...       ... ..... .....
     ..... ...... ...     ... ...... .....
     ..... ....... ...   ... ....... .....
     ..... ........ ... ... ........ .....
     ...... ........ ..... ........ ......
     ...... ......... ... ......... ......
     ....... ........./\ ......... .......
     .......  .......|  |........  .......
     ........ .................. ........
     ......... ................ .........
     ..........  .............  ..........
     ............  .........   ...........
     ..............         ..............
     .....................................
     .....................................
     .....................................
     .....................................
     .....................................
"""
batterDec = 0
pitcherDec = 0
outs = 0
inning = 0
#.5 will be top of the inning and 1 will be bottom
runsGuest = 0
#if the inning count is a decimal you will add runs to guest. 4 hits to get the first run after that every hit is a run (this is per inning)
runsHome = 0
#if the inning count is a whole number you add runs to home.
#_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
def PitcherChoice():
    x = 1
    while x > 0:
        print(battersBox,"ok pitcher where would you like to throw?")
        pitcherDec = input()
        y = input("Are you sure?(yes or no)")
        if y.upper() == "YES":
            x = 0
            

#__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
print("\n\n\n\n                 Welcome to Baseball Mania 1!\nChoose who is Guest(batting first) and who is Home(pitching first)")
input("Click enter when you are ready\n")
print("Now how this game works is the pitcher will decide where to throw a pitch. Then the batter will guess where the pitch will be.\nIf the batter guesses right they get a hit and a man on base. If they guess wrong they will get a strike, three strikes is an out and 3 outs switch sides")
input("Hit enter when you are ready to conitinue")
print(field,"\n\n Now guest(batter) turn around and pitcher(home) hit enter when you are ready")
input()
PitcherChoice()
clear_terminal()

